version: '3'
services:
  rabbitmq:
    image: rabbitmq:4.0.4-management-alpine # tells docker which image to pull
    container_name: 'rabbitmq'
    ports:
        - 5672:5672 # port to interact with queue
        - 31074:5672/tcp
        - 15672:15672 # port to web UI
    environment:
            RABBITMQ_DEFAULT_PASS: admin
            RABBITMQ_DEFAULT_USER: admin
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_net
networks:
  rabbitmq_net: